# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

jobs:
  include:
    - stage: test
      r: oldrel
    - stage: test
      r: devel
    - stage: test
      r: release
    - stage: deploy
      r: devel
      if: branch = master
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: false
        local-dir: docs
      r_binary_packages:
        - pkgdown
      script:
        - Rscript -e 'pkgdown::build_site()'

warnings_are_errors: false

r_binary_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
