# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
    - stage: test
      r: oldrel

    - stage: test
      r: release
      r_binary_packages:
        - covr
      after_success:
        - Rscript -e 'covr::codecov()'

    - stage: test
      r: devel
      warnings_are_errors: false

    - stage: deploy
      r: release
      if: branch = master
      r_binary_packages:
        - pkgdown
      after_success:
        - Rscript -e 'pkgdown::build_site()'
      deploy:
        provider: pages
        local-dir: docs
        skip-cleanup: true
        keep-history: false
        github-token: $GITHUB_TOKEN
