# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

jobs:
  include:
    - stage: test
      r: oldrel

    - stage: test
      r: devel

    - stage: test
      r: release
      r_binary_packages:
        - covr
      after_success:
        - Rscript -e 'covr::codecov()'

    - stage: deploy
      r: devel
      if: branch = master
      r_binary_packages:
        - pkgdown
      after_success:
        - Rscript -e 'pkgdown::build_site()'
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: false
        local-dir: docs
